name: Terraform Deploy + Upload README
env:
TF_WORKING_DIR: terraform
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Configure AWS credentials
uses: aws-actions/configure-aws-credentials@v2
with:
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
aws-region: ${{ secrets.AWS_REGION }}


- name: Setup Terraform
uses: hashicorp/setup-terraform@v2
with:
terraform_version: 1.6.0


- name: Terraform Init
working-directory: ${{ env.TF_WORKING_DIR }}
run: terraform init -input=false


- name: Terraform Validate
working-directory: ${{ env.TF_WORKING_DIR }}
run: terraform validate || true


- name: Terraform Plan
working-directory: ${{ env.TF_WORKING_DIR }}
run: terraform plan -out=tfplan -input=false


- name: Terraform Apply
working-directory: ${{ env.TF_WORKING_DIR }}
run: terraform apply -input=false -auto-approve tfplan


- name: Get outputs
id: tf_outputs
working-directory: ${{ env.TF_WORKING_DIR }}
run: |
echo "::set-output name=bucket::$(terraform output -raw bucket_name)"
echo "::set-output name=dist_id::$(terraform output -raw cloudfront_distribution_id)"
echo "::set-output name=dist_domain::$(terraform output -raw cloudfront_domain_name)"


- name: Upload README to S3
run: |
aws s3 cp README.md s3://${{ steps.tf_outputs.outputs.bucket }} --acl private


- name: Create CloudFront invalidation
if: steps.tf_outputs.outputs.dist_id != ''
run: |
aws cloudfront create-invalidation --distribution-id ${{ steps.tf_outputs.outputs.dist_id }} --paths "/README.md" || true